Revert "chore(api/lua): renames rockspec file to facilitate install"
This reverts commit d5a42b2501651e2a21164045c46453eb5325dc1f.

Error: Expected filename in format 'name-version-revision.rockspec'.